// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TEST1_TESTFLAT_H_
#define FLATBUFFERS_GENERATED_TEST1_TESTFLAT_H_

#include "flatbuffers/flatbuffers.h"


namespace TestFlat {

struct StcTestMessage1;

struct StcTestMessage1 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_NAME = 6,
    VT_AGE = 8
  };
  uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(VT_NAME); }
  uint32_t age() const { return GetField<uint32_t>(VT_AGE, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyField<uint32_t>(verifier, VT_AGE) &&
           verifier.EndTable();
  }
};

struct StcTestMessage1Builder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) { fbb_.AddElement<uint32_t>(StcTestMessage1::VT_ID, id, 0); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(StcTestMessage1::VT_NAME, name); }
  void add_age(uint32_t age) { fbb_.AddElement<uint32_t>(StcTestMessage1::VT_AGE, age, 0); }
  StcTestMessage1Builder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  StcTestMessage1Builder &operator=(const StcTestMessage1Builder &);
  flatbuffers::Offset<StcTestMessage1> Finish() {
    auto o = flatbuffers::Offset<StcTestMessage1>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<StcTestMessage1> CreateStcTestMessage1(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t id = 0,
   flatbuffers::Offset<flatbuffers::String> name = 0,
   uint32_t age = 0) {
  StcTestMessage1Builder builder_(_fbb);
  builder_.add_age(age);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const TestFlat::StcTestMessage1 *GetStcTestMessage1(const void *buf) { return flatbuffers::GetRoot<TestFlat::StcTestMessage1>(buf); }

inline bool VerifyStcTestMessage1Buffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<TestFlat::StcTestMessage1>(); }

inline void FinishStcTestMessage1Buffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<TestFlat::StcTestMessage1> root) { fbb.Finish(root); }

}  // namespace TestFlat

#endif  // FLATBUFFERS_GENERATED_TEST1_TESTFLAT_H_
